# Generated by Django 4.2.18 on 2025-02-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vps',
            options={'verbose_name': 'Виртуальный сервер (VPS)', 'verbose_name_plural': 'Виртуальные сервера (VPS)'},
        ),
    ]
